language: ruby

cache: bundler

before_install:
- gem install bundler

script:
- bundle exec rspec spec
- bundle exec bin/spec > spec.json
- git diff --stat --exit-code
- git diff --stat --cached --exit-code
